site_name: 'Nokul Dokümantasyonu'
site_description: 'Nokul Projesi Dokümantasyonu'
repo_name: omu/nokul
repo_url: https://github.com/omu/nokul/tree/develop
copyright: 'Bu sitede yayınlanan dokümanlar <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC Attribution-ShareAlike 3.0 Unported</a> ile lisanslanmıştır.'
docs_dir: doc
markdown_extensions:
  - codehilite:
      linenums: false
  - extra
  - mdx_truly_sane_lists
  - pymdownx.superfences
theme:
  name: material
  language: tr
  logo:
    icon: pages
  palette:
    primary: blue grey
    accent: indigo
plugins:
  - search:
      lang: tr
extra:
  social:
    - type: github
      link: https://github.com/omu
    - type: linkedin
      link: https://linkedin.com/company/omu-baum
nav:
  - Uygulama İç Yapısı:
    - Kullanıcılar: app/user.md
    - Birimler: app/unit.md
    - Patron: app/patron.md
  - Geliştirme:
    - Rake Görevleri: development/tasks.md
    - Testler: development/tests.md
    - Seed İşlemleri: development/seeds.md
    - Sırlar: development/secrets.md
    - Docker: development/docker.md
    - Vagrant: development/vagrant.md
  - Yardımcılar:
    - Birim Testler: helpers/unit-test.md
    - link_to_helper: helpers/link_to_helper.md
    - dynamic_select: helpers/dynamic_select.md
  - Operasyonlar:
    - Kurulum: operations/installation.md
    - Güncelleme: operations/upgrading.md
    - Konuşlandırma: operations/deployment.md
  - Eklentiler:
    - Support:
      - Codification: plugins/support/codification.md
      - Collection: plugins/support/collection.md
      - Rest Client: plugins/support/rest_client.md
      - Sensitive: plugins/support/sensitive.md
      - Structure: plugins/support/structure.md
      - Uniq Collection: plugins/support/uniq_collection.md
      - Çekirdek Eklentileri: plugins/support/core_ext.md
    - Tenant:
      - Ortak:
        - Geliştirme:
          - Nokul::Tenant::Codification: plugins/tenant/common/development/codification.md
          - Nokul::Tenant: plugins/tenant/common/development/tenant.md
          - Nokul::Tenant::Units: plugins/tenant/common/development/units.md
        - Spesifikasyonlar:
          - Kullanıcıların İsimlendirilmesi: plugins/tenant/common/specification/user-names.md
          - Öğrencilerin Numaralandırılması: plugins/tenant/common/specification/student-numbers.md
          - Birim Kısaltmaları: plugins/tenant/common/specification/unit-abbreviations.md
          - Birimlerin Kodlanması: plugins/tenant/common/specification/unit-codes.md
