require: rubocop-performance
require: rubocop-rails

Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Documentation:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test
Metrics/LineLength:
  Max: 120
  Exclude:
    - app/validators/employee_validator.rb # Won't fix
Metrics/BlockLength:
  Exclude:
    - config/routes/**/*
    - lib/tasks/**/*.rake
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - app/models/unit.rb # TODO: Workaround until refactor
AllCops:
  TargetRubyVersion: 2.6
  # Do not exclude files from ALL COPS unless it's really necessary!
  Exclude:
    - app/controllers/concerns/yoksis_resource.rb
    - bin/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/*.rb
    - config/routes.rb
    - node_modules/**/*
    - Vagrantfile
    - vendor/bundle/**/*
