Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Lambda:
  Enabled: false
Documentation:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - beta
Metrics/LineLength:
  Max: 120
  Exclude:
    - app/validators/employee_validator.rb # Won't fix
Metrics/BlockLength:
  Exclude:
    - config/routes/**/*
    - lib/tasks/**/*.rake # Won't fix
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
AllCops:
  TargetRubyVersion: 2.6
  # Do not exclude files from ALL COPS unless it's really necessary!
  Exclude:
    - app/controllers/concerns/reference_resource.rb
    - bin/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/*.rb
    - config/routes.rb
    - Vagrantfile
