default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  url: <%= Rails.application.database_url_for('development') %>

test:
  <<: *default
  url: <%= Rails.application.database_url_for('test') %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>

beta:
  <<: *production
