# https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job
# first_job:
#   cron: "* * * * *" # execute at every minute
#   class: SidekiqRakeJob
#   queue: high
#   args:
#     name: fetch:reference
#     params:
#       - administrative_functions
#       - AdministrativeFunction
